#!/bin/sh

echo "Running ktlint check..."

./gradlew ktlintCheck --daemon

status=$?

if [ "$status" = 0 ] ; then
    echo "ktlint check ran successfully."
else
    echo "ktlint check failed. Formatting with ktlint..."
    ./gradlew ktlintFormat
    exit 1
fi

echo "Running unit tests..."

./gradlew testDebugUnitTest --daemon

status=$?  # Update the status after running unit tests

if [ "$status" = 0 ] ; then
    echo "Unit tests ran successfully."
    exit 0
else
    echo "Unit tests failed."
    exit 1
fi