name: Pull request CI checks

on: [pull_request]

jobs:
  build:
    name: Gradle build
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  lint:
    name: Lint checks
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Ktlint
        run: ./gradlew ktlint
      - name: Lint
        run: ./gradlew lint

  test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Fonts
        run: |
          pip install --upgrade fonttools
          bash ./scripts/validate_fonts.sh
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit-test-report
          path: ./**/build/reports/tests/testDebugUnitTest/